version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: db
    environment:
      POSTGRES_DB: fire_detection
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  dashboard:
    build: .
    container_name: dashboard
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://root:root@db:5432/fire_detection
      - HOST=0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
